### ISSUE TITLE
Add ability to list commits on all the branches in git repos

### ISSUE THREAD

**Issue by eramdam** [notwaldorf/tiny-care-terminal#105]
Currently the gitlog widgets seem to list/count commits from only the current branch(es) the scanned git repos are in.
This might result in a "non-accurate" count of commits if you switch branches frequently inside your project(s).

Apparently the `gitlog` package has an [option](https://github.com/domharrington/node-gitlog#all) for that so I feel like it could be easy to add.

Thoughts?

**Comment by mojoaxel** [comment]
🥇 I think that's a good idea!

It's the ["all" option](https://github.com/domharrington/node-gitlog#all).

**Comment by Tardog** [comment]
Maybe not everyone will want to see all commits across branches (although I certainly do). How about a configuration option to toggle this behaviour?

**Comment by mojoaxel** [comment]
> How about a configuration option to toggle this behaviour?

@notwaldorf What do you think?

**Comment by Charlotteis** [comment]
Is the closing of this issue because it's not something we can do? :) I'd love this feature!
