### ISSUE TITLE
Say box corrupted text

### ISSUE THREAD

**Issue by Lexicality** [notwaldorf/tiny-care-terminal#112]
- **Node Version**: v6.10.3
- **tiny-core-terminal version**: 1.3.1
- **Shell**: zsh
- **Terminal Program**: iterm
- **Operating System**: Mac

Some times the say box dissolves into garbage. Possibly it's trying to render two lines of text?
(Also emojis render at half-width but I think that's my font)

<img width="639" alt="screen shot 2017-07-07 at 15 45 57" src="https://user-images.githubusercontent.com/847422/27963095-d5a983f8-632b-11e7-834c-47f232205aea.png">

**Comment by Lexicality** [comment]
It just restored itself. I've notice it do this a couple of times in the past too.

<img width="632" alt="screen shot 2017-07-07 at 15 52 08" src="https://user-images.githubusercontent.com/847422/27963232-442be550-632c-11e7-8691-674a707e9eac.png">

**Comment by Lexicality** [comment]
Possibly it restored because I opened a new tab to check the versions and that resized the program? You can see that the box takes up a different amount of space on the background image between the two pictures.

After opening and closing a new tab several times I noticed that the green bar in the top right only appears when the terminal is slightly shorter than full screen.

**Comment by notwaldorf** [comment]
Yeah I think that this may be a problem with `blessed-contrib` or something, where it tries to repaint a new screen, but doesn't clear the old one entirely. I think you can also refresh by pressing `r`, btw.

**Comment by Lexicality** [comment]
`r` refreshes git but not the say box.
FWIW I _think_ this only happens when it updates whilst iTerm is in a different space.

**Comment by Lexicality** [comment]
<img width="1280" alt="screen shot 2017-09-25 at 11 50 42" src="https://user-images.githubusercontent.com/847422/30805259-8c53ccb2-a1e8-11e7-9fdb-76e8277ed811.png">
I can confirm this does also happen while the terminal is in focus as I got to witness this particular implosion first hand.

Unless the three-eyed-raven parrot is intentional, a way to completely repaint without having to kill and restart the process would be handy. 🙂
