### ISSUE TITLE
No commits showing

### ISSUE THREAD

**Issue by dreamsparkx** [notwaldorf/tiny-care-terminal#115]
I installed everything properly.
All the tweets are showing.
But the commits are not.
It is showing the following in the today dialog box:
Could not open directory directory: /Users/gauravbharti/Xcode/junkart-ios'
And for clarification:
```
echo $TTC_REPOS
‘~/AndroidStudioProjects/junkart-user-app,~/Xcode/junkart-ios’
```

**Comment by mojoaxel** [comment]
It has problems opening `~/Xcode/junkart-ios', but not `~/AndroidStudioProjects/junkart-user-app`? Make sure you have permissions to access the XCode directory:
```sh
cd ~/Xcode/
ls -la
```

**Comment by yanshiyason** [comment]
For some reason, I had to install this dependency globally:

```
npm install -g git-standup
```

the `package.json` lists it as a dependency.. but for some reason `install -g tiny-care-terminal` didn't install it..

**Comment by mojoaxel** [comment]
> Perhaps someone just forgot to version bump and publish?

@notwaldorf Please make a new release if you find the time. Thx!
