### ISSUE TITLE
Why does it show yesterdays commits in "Today"?

### ISSUE THREAD

**Issue by cvuorinen** [notwaldorf/tiny-care-terminal#122]
Seems weird to me that when I open it up in the morning it says I have lots of commits in the "Today" box as well as the today column in the "Commits" box that are from yesterday.

Should the counting of today's commits be by current date instead? Could there be a separate box/column for yesterday? Or if the preferred functionality is the current one, could it be renamed to "Last 24 hours"/"24h" for example?

**Comment by mojoaxel** [comment]
I thinks the easiest fix would really be to rename [the Today](https://github.com/notwaldorf/tiny-care-terminal/blob/3b00be1a00b9b02dd5439d7e423088335be01639/care.js#L87) into something like "Last 24 hours".

@cvuorinen Maybe you can create a pull request. It was your idea 😉
