### ISSUE TITLE
Don't see git commits in tmux compared to bash

### ISSUE THREAD

**Issue by archaeogeek** [notwaldorf/tiny-care-terminal#123]
I've got tiny-care-terminal installed and working fine in bash. However when I switch to tmux, everything displays apart from the git commits. I've checked that the environment variables are set correctly in tmux, by echoing them. I've also checked the versions of node and tiny-care-terminal in both bash and tmux and they both return the same values.

- **Node Version**: `node --version`
v4.2.6

- **tiny-core-terminal version**: `npm info tiny-care-terminal | grep version:`
1.3.2 

- **Shell**: `bash, zsh, fish, something else?`
bash

- **Terminal Program**: `tmux, iterm, terminator, cmd, something else?`
tmux

- **Operating System**: `Mac, Windows, Linux, BSD, Really, something else?`
Linux- Ubuntu Gnome

Thank you!

**Comment by mojoaxel** [comment]
Please update node.js to a version >= 6.10.3. 
See https://github.com/notwaldorf/tiny-care-terminal/blob/master/package.json#L9

**Comment by archaeogeek** [comment]
I'd share a screenshot but the upgrade worked- thanks!
