### ISSUE TITLE
Longer tweets are getting cut off, links not separated?

### ISSUE THREAD

**Issue by fluxsauce** [notwaldorf/tiny-care-terminal#141]
Not sure if this is a `tiny-care-terminal` issue or the Twitter API.

- **Node Version**: `v6.13.1`
- **tiny-care-terminal version**: `1.3.2`
- **Shell**: `bash`
- **Terminal Program**: `iterm`
- **Operating System**: `Mac`

This is happening when web scraping is off, so with the API keys. I tried and honestly couldn't replicate it with scraping turned on.

![screen shot 2018-03-22 at 9 37 39 am](https://user-images.githubusercontent.com/976391/37784308-b34be8a6-2db4-11e8-9eb5-282243072eae.png)

Status in question: https://twitter.com/i/web/status/975425756535824384

Shortened URL it's displaying: https://t.co/Eop5F6Wxg0

There's a different issue when there's an image. I don't expect `tiny-care-terminal` to render the image, but there's no space before the link.

![screen shot 2018-03-22 at 9 44 00 am](https://user-images.githubusercontent.com/976391/37784821-ed267842-2db5-11e8-8b81-66522f624966.png)

The tweet in question, which is pretty rude so I won't directly link to it, is basically

```
Eat arbys

(embedded image)
```

```
https://twitter.com/nihilist_arbys/status/959543365116354562
```

**Comment by mojoaxel** [comment]
@fluxsauce Have you tried some other "Artwork" like e.g. `parrot` or `panda`?

**Comment by fluxsauce** [comment]
`panda` scraped (exhibits the unseparated links):

https://twitter.com/nihilist_arbys/status/838863899021742080

![screen shot 2018-03-22 at 1 11 59 pm](https://user-images.githubusercontent.com/976391/37795851-e2760efe-2dd2-11e8-8ada-eb8290cd7ba8.png)

---

`parrot` scraped (handles the long length correctly, so maybe there's an API problem?)

This is interesting in that the width of the bounding text box is kind of messed up but it actually handled the longer length of content without any problems (178 characters). Not seeing the parrot itself isn't a bug given the number of line breaks and the height of the window.

https://twitter.com/nihilist_arbys/status/971416599449296896

![screen shot 2018-03-22 at 1 16 01 pm](https://user-images.githubusercontent.com/976391/37795957-3085c7e2-2dd3-11e8-85a6-8e68b3e37069.png)

**Comment by fluxsauce** [comment]
For the shortening - https://developer.twitter.com/en/docs/tweets/tweet-updates `tweet_mode=extended`

**Comment by mojoaxel** [comment]
@fluxsauce Thanks very much for your support! I've created a fix for this issue: #143

**Comment by mojoaxel** [comment]
> This is interesting in that the width of the bounding text box is kind of messed up but it actually handled the longer length of content without any problems (178 characters)

There is already an issue for that: https://github.com/gauravchl/ansi-art/issues/6

**Comment by mojoaxel** [comment]
@fluxsauce Thanks again for finding AND fixing this issue! :hand:

**Comment by mapodev** [comment]
can you please give an example of using `tweet_mode=extended`

**Comment by fluxsauce** [comment]
> can you please give an example of using `tweet_mode=extended`

This is out of scope of this issue, but see https://github.com/notwaldorf/tiny-care-terminal/issues/141#issuecomment-706347420 for the diff and the usage. If you have any other questions, please use the issue queue within https://github.com/ttezel/twit
