### ISSUE TITLE
Only show user's own commits?

### ISSUE THREAD

**Issue by hackjutsu** [notwaldorf/tiny-care-terminal#144]
- **Node Version**: `v9.5.0`
- **tiny-core-terminal version**: `1.3.2`
- **Shell**: `zsh` 
- **Terminal Program**: `iterm`
- **Operating System**: `Mac`

tiny-care-terminal seems to show all recent commits from different contributors. Is there a configuration to show user's own commits?

Thanks!

**Comment by mojoaxel** [comment]
At the moment only the local User is used: 
https://github.com/notwaldorf/tiny-care-terminal/blob/master/gitbot.js#L78

@hackjutsu Are you sure the commits are from different users?

**Comment by hackjutsu** [comment]
@mojoaxel Thanks for the response:) It turns out that if I haven't set `user.name`, it'll show all commits.
