### ISSUE TITLE
"RangeError: Invalid count value" since updating node

### ISSUE THREAD

**Issue by Lexicality** [notwaldorf/tiny-care-terminal#147]
- **Node Version**: `v9.11.1`
- **tiny-core-terminal version**: `1.3.2`
- **Shell**: `zsh`
- **Terminal Program**: `iTerm`
- **Operating System**: `macOS 10.12.6`

![screen-shot-2018-04-23-at-15 43 33](https://user-images.githubusercontent.com/847422/39134099-bb753e98-470d-11e8-91b8-3a519fe8de90.jpg)

I updated from node 8.1 to 9.11 and now `tiny-care-terminal` doesn't start properly.

```
(node:42726) UnhandledPromiseRejectionWarning: RangeError: Invalid count value
    at String.repeat (native)
    at lines.map.line (/usr/local/lib/node_modules/tiny-care-terminal/node_modules/node-chat-bubble/index.js:38:30)
    at Array.map (<anonymous>)
    at Object.getBox [as get] (/usr/local/lib/node_modules/tiny-care-terminal/node_modules/node-chat-bubble/index.js:36:17)
    at Object.get (/usr/local/lib/node_modules/tiny-care-terminal/node_modules/ansi-art/src/index.js:23:42)
    at getAnsiArt (/usr/local/lib/node_modules/tiny-care-terminal/care.js:325:30)
    at /usr/local/lib/node_modules/tiny-care-terminal/care.js:136:29
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:42726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mojoaxel** [comment]
I can not reproduce this on linux within [Hyper](/zeit/hyper) using node v9.11.1 and npm v5.6.0.
Can please anybody try this on macOS!?

@Lexicality Please make sure to use npm v5.6 and reinstall all npm modules (`rm -rf node_modules && npm install`).

**Comment by KaraAJC** [comment]
I'm actually getting that error too, and Here are my specs: 

**Node Version:** `v9.6.1`
**tiny-core-terminal version:** `1.3.2`
**Shell:** `bash`
**Terminal Program:** `terminal`
**Operating System:** `macOS 10.13.4`

**Comment by Lexicality** [comment]
I am using npm 5.6 and this was actually the first node module I installed after upgrading to 9 wiped my modules folder.
After a bit of digging, it's because `wrapAnsi` considers emoji to be one character wide, but `str.length` considers them to be 2 or more characters wide.

```javascript
  let lines = wrapAnsi(message, boxWidth - 4, { hard: true }).split(/\n/);

  // Add vertical borders and paddings
  lines = lines.map(line => {
    const rightPaddingCount = boxWidth - 4 - line.length;
    const rightPadding = " ".repeat(rightPaddingCount);
    return boxChars.vertical + " " + line + " " + rightPadding + boxChars.vertical;
  });
```

A line that's exactly `boxWidth - 4` characters long including an emoji, `boxWidth - 4 - line.length` produces a negative value and `" ".repeat(rightPaddingCount)` throws.

**Comment by mojoaxel** [comment]
@Lexicality That's interesting! Thanks for diving into it!

This is definitely not an issue of `tiny-care-terminal` and should be fixed in the underlying library.
@Lexicality Could you open an issue in [the ansi-art repository](https://github.com/gauravchl/ansi-art)!?

**Comment by gauravchl** [comment]
@Lexicality @mojoaxel Here is the fix: https://github.com/notwaldorf/tiny-care-terminal/pull/149

Cheers!!

ref: https://github.com/gauravchl/node-chat-bubble/pull/1

**Comment by bharath2232** [comment]
****
