### ISSUE TITLE
App Crashes On Start

### ISSUE THREAD

**Issue by TheGalacticNinja** [notwaldorf/tiny-care-terminal#151]
Hey Guys! Love the app and have been a long time user! Ran into a interesting problem though upon updating and testing.

I am using the most up to date version of tiny-care-terminal but it crashes upon opening. So I see the screen for a split then this error pops up. 

![image](https://user-images.githubusercontent.com/6441142/40511405-94760fa2-5f6d-11e8-97b6-76cfe60bf61c.png)

There were also warnings and issues upon installing the package globally with npm and the rebuild. Now the interesting thing is if I revert to 1.3.2 it works perfectly with my setup. I also tried a couple different versions of node with this going between current and stable, the same issue pops up. 

- **Node Version**: `8.11.2`
- **tiny-core-terminal version**: `1.4.2`
- **Shell**: `bash`
- **Terminal Program**: `Hyper`
- **Operating System**: `Mac`

For now I will use 1.3.2, I can't work properly without this app lol. Hopefully though this is just an issue with my machine. Let me know if you guys need any other details. Could be a problem on my end and I'll try to figure out the exact problem.

**Comment by notwaldorf** [comment]
Hiya -- this seems to be a problem introduced in 1.4.0. I haven't looked into it yet, but the problem seems to be with the paths you have for your repos. You probably have a relative path like `~/Code`; if you convert that to the full qualified path (`/Users/foo/Code` the crash goes away.

Sorry about that!

**Comment by mojoaxel** [comment]
I'll have a closer look on the weekend. Sorry for introducing this!

**Comment by TheGalacticNinja** [comment]
@notwaldorf alrighty that did the trick 😄 Also sorry didn't notice the bug was listed in your Readme. I'll try to keep an eye for the ones that pop up in it next time.

**Comment by notwaldorf** [comment]
@thegalacticninja whew glad it worked

@mojoaxel no worries at all!
