### ISSUE TITLE
Installation fails because it needs python2.x instead of python 3.x

### ISSUE THREAD

**Issue by robinfla** [notwaldorf/tiny-care-terminal#155]
Hi, 

I've stumbled across a problem this morning trying to install tiny care terminal. I ran into this error message: 

```
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/git2.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/git-utils
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! git-utils@5.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@5.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

- **Node Version**: `9.4.0`
- **tiny-core-terminal version**: `1.4.1`
- **Shell**: `zsh`
- **Terminal Program**: `tmux / iterm`
- **Operating System**: `Mac High Sierra 10.13.6`

It appeared that the problem originated from git-utils installation. Looking for issues in the git-utils repo I've found one that matched my problem: https://github.com/atom/git-utils/issues/72

The issue apparently comes from node-gyp that does not support python 3.x. I then installed python 2.7, ran the installation again and this time, it worked. 

I don't want python 2.7 as default on my machine as I'm afraid it'll wreak havoc so I ran this command afterwards: 
`unlink /usr/local/bin/python
ln -s /usr/local/bin/python3.6 /usr/local/bin/python` to change the symlink to point to the python 3.6 exec. 

tiny-care-terminal still launches with python 3.6 so everything's good.

It's not really an issue but I though it might come in handy if someone runs into the same problem :) 
Feel free to close if it's irrelevant & thanks for your work, can't wait to use the dashboard !

**Comment by mojoaxel** [comment]
@robinfla Here is a late thank you for posting this detailed explanation! :heart_decoration: 

But because it seems to be an `gyp-mac` problem I think we can close this here.

**Comment by spiritphyz** [comment]
I also had a lot of node-gyp problems installing on Ubuntu 16.04 with Node v12.3.1.

I had to downgrade Node and Python (temporarily). I can install it successfully with:
```bash
nvm use v10.15.3
npm config set python python2.7
export PYTHON=python2.7
npm i -g —python=python2.7 tiny-care-terminal

npm config set python python3
export PYTHON=/usr/bin/python3
tiny-care-terminal
```

I’m still not able to install the app with Node v12.3.1. I guess the install always fails at a node-gyp and python3 incompatibility.
