### ISSUE TITLE
Error with Twitter bot

### ISSUE THREAD

**Issue by HugoLiconV** [notwaldorf/tiny-care-terminal#157]
Please include the template below to ensure a more accurate response to your issue.

- **Node Version**: `v8.11.1`
- **tiny-core-terminal version**: `1.4.1`
- **Shell**: `zsh`
- **Terminal Program**: `iterm`
- **Operating System**: `Mac`
![captura de pantalla 2018-10-28 a la s 2 21 42 p m](https://user-images.githubusercontent.com/22970186/47621994-d52cf400-dabc-11e8-853e-43eac1ec9cd6.png)

Thank you!

**Comment by mojoaxel** [comment]
This is obviously a problem with the twitter feature: https://github.com/notwaldorf/tiny-care-terminal/blob/master/care.js#L147

@HugoLiconV Would you share which twitter feeds you are using?

**Comment by HugoLiconV** [comment]
@mojoaxel I'm using the defaults

**Comment by mojoaxel** [comment]
@HugoLiconV ok, thanks. Do you still experience this problem or was this a one-time-thing?

**Comment by mojoaxel** [comment]
Ah I see! The spaces are the problem!
This is obviously a bug,  let me fix that...

Nice catch! Thanks for reporting!

**Comment by HugoLiconV** [comment]
Yes, the spaces were the problem. I removed them and it's working. Thanks 👍
