### ISSUE TITLE
Comma seperated list of Repos not working

### ISSUE THREAD

**Issue by steoneill** [notwaldorf/tiny-care-terminal#161]
I've set my repos with set -gx `TTC_REPOS '/Users/Ste/react,/Users/Ste/valet'` and it stops finding repos. Single folders seem to work.

- **Node Version**: 10.9.0
- **tiny-core-terminal version**: 1.4.1
- **Shell**: fish
- **Terminal Program**: iterm
- **Operating System**: MacOS 

Thank you!

**Comment by mojoaxel** [comment]
:tada:

**Comment by mojoaxel** [comment]
Could someone please confirm, that this is an issue on MacOS. Thx!
