### ISSUE TITLE
Cannot add repos to TTC_REPOS if the path contains a space

### ISSUE THREAD

**Issue by wilhelmklopp** [notwaldorf/tiny-care-terminal#17]
Hello 👋 Loooove this app so much!!! 💖 

Currently, it seems like you cannot add any paths that contain a space to the TTC_REPOS environment variable.

**Comment by notwaldorf** [comment]
Oh yeah you're totally right. I use the space as delimiters. I'm gonna add a "depth" argument soon so that you can just use the parent director you instead

**Comment by notwaldorf** [comment]
`tiny-care-terminal@1.1.0` now has a `TTC_REPOS_DEPTH` argument, so I'm going to optimistically mark this as closed (otherwise i'd have to switch from spaces to commas and break all the existing users 😭)

**Comment by wilhelmklopp** [comment]
Thanks, I think that will help a lot of people!

In my case, the space is quite early on in the path. It looks something like this: `/home/wilhelm/Google Drive/folder/folder/folder/folder/actualProject`

So I think it would take forever to check every folder in my Google Drive for .git directories.

If a character that's typically not allowed in paths was to be the delimiter, would that still break things for existing users? Maybe a character like `|`

**Comment by notwaldorf** [comment]
Oh! Good news: this is only broken because I wrote dumb code, and the instructions actually tell you to use commas and not spaces. Gimme a sec.

**Comment by wilhelmklopp** [comment]
ooo 😁 

To clarify: I meant keep commas as the delimiter in the environment variable, but use a more sepcial character to split here: https://github.com/notwaldorf/tiny-care-terminal/blob/0e7d6ae65953bc8348406f65b70d0bbe60a1e384/config.js#L14

**Comment by notwaldorf** [comment]
Well, that's not the problem, this is the problem: https://github.com/notwaldorf/tiny-care-terminal/blob/master/standup-helper.sh#L33

the shell script takes "everything that wasn't passed to -d or -m" to be directory names, and because they're space separated, it's fine. If they're separated by a different delimiter, I have to do a bash hack to get around that (like split the string. everything in bash is a hack 😅)

**Comment by kzap** [comment]
same problem here
