### ISSUE TITLE
Sample.env not being used?

### ISSUE THREAD

**Issue by tw88** [notwaldorf/tiny-care-terminal#19]
Hi,

i have the problem that i have to change the care.js file in order to apply settings. The .env File seems to be ignored here (for every setting).

**Comment by billhimmelsbach** [comment]
Not sure if this helps you, but I interpreted the sample.env as an example for what environmental variables you would add, such as in your bash profile (~/.bash_profile on my Mac). For instance, I added the following lines to my bash profile:

```
export TTC_BOTS='tinycarebot,selfcare_bot,rikergoogling'
export TTC_REPOS='~/repos/'
export TTC_WEATHER='Oakland, CA'
```

**Comment by tw88** [comment]
Ha i should have tried that :) Works perfect thanks a lot.
