### ISSUE TITLE
Instructions for simple humans

### ISSUE THREAD

**Issue by MichielBijl** [notwaldorf/tiny-care-terminal#21]
Hi, I’m a simple human that uses the terminal quite a bit to commit stuff while trying not to break the repo. Tiny Care Terminal seems like a great way to have a prettier and more useful terminal window somewhere on screen. However, after doing the NPM dance, I have no clue how to configure it, where is this `.env` file you speak of? 🤔

Oh, and thank you for making this 🙌🏽.

**Comment by IronistM** [comment]
Hi!

You can open your `.bashrc` file (located in your home folder but hidden) and add the following

```bash
## This is the tiny-care-terminal configuration variables
# List of accounts to read the last tweet from, comma separated
# The first in the list is read by the party parrot.
export TTC_BOTS='tinycarebot,selfcare_bot,magicrealismbot'

# List of folders to look into for `git` commits, comma separated.
export TTC_REPOS='~/Documents/Github'

# Location/zip code to check the weather for. Both 90210 and "San Francisco, CA"
# should be ok. It's using weather.service.msn.com behind the curtains.
export TTC_WEATHER='Athens'

# Set to false if you're an imperial savage. <3
export TTC_CELSIUS=true

# Unset this if you _don't_ want to use Twitter keys and want to
# use web scraping instead.
export TTC_APIKEYS=true

# Refresh the dashboard every 20 minutes.
export TTC_UPDATE_INTERVAL=10

# Twitter api keys
export CONSUMER_KEY='...'
export CONSUMER_SECRET='...'
export ACCESS_TOKEN='...'
export ACCESS_TOKEN_SECRET='...'
```

You can check if they are working in the terminal

```bash
$ printenv | grep TTC_*
TTC_BOTS=tinycarebot,selfcare_bot,magicrealismbot
TTC_APIKEYS=true
TTC_WEATHER=Athens
TTC_CELSIUS=true
TTC_UPDATE_INTERVAL=10
TTC_REPOS=~/Documents/Github
```

Then open `tiny-care-dashboard`

```bash
$ tiny-care-dashboard
```

Hope this helps a bit.

**Comment by OGKevin** [comment]
After following [this](https://apple.stackexchange.com/questions/181562/how-to-find-bashrc-or-zshrc) guide and creating the `.bashrc`file my self and pasting the configuration lines.. still doesn't work 😔 i mean the app works but cant configure it.

`$ printenv | grep TTC_*` returns nothing but `$ printenv ` does return some other configurations.

**Comment by OGKevin** [comment]
If you place it in `bash_profile` it seems to work.

**Comment by notwaldorf** [comment]
I'll add a couple more instructions where to put these variables. Thanks!

**Comment by notwaldorf** [comment]
Added some instructions in 6a53e22
