### ISSUE TITLE
TTC boxes collapse weirdly in Hyper terminal.

### ISSUE THREAD

**Issue by patrickoliveras** [notwaldorf/tiny-care-terminal#27]
![image](https://cloud.githubusercontent.com/assets/11946875/25214101/044163f2-255b-11e7-8b3d-9df4feb53a50.png)

Perhaps this should be warned or added in the ReadMe file. Not sure if it's a font issue. (?)

**Comment by notwaldorf** [comment]
Woof, I wonder if this is a problem with `blessed-contrib` (the thing that I use to draw the boxes)
I'll try to install hyper term and see if their demos work there

**Comment by patrickoliveras** [comment]
Hadn't seen that lib, it's cool. Alright so I took a look at it and seems like the issue is with blessed-contrib and the issue has been submitted. And now the waiting begins!

**Comment by notwaldorf** [comment]
Thanks! I'll close this one, i guess, since there's nothing I can do about it :(
