### ISSUE TITLE
Lots of problems standup-helper.sh

### ISSUE THREAD

**Issue by Josephvb10** [notwaldorf/tiny-care-terminal#37]
> **Node Version**: `node --version` 6.10.2
> **tiny-core-terminal version**: `npm info tiny-care-terminal | grep version:`
> **Shell**: `bash, zsh, fish, something else?` 1.0.8
> **Terminal Program**: `tmux, iterm, terminator, cmd, something else?` bash
> **Operating System**: `Mac, Windows, Linux, BSD, Really, something else?` Linux

Relying on (npm -g bin) to get the bin directory seems to be pretty unreliable as in my system when I execute the command I get the folder but also below  that

```
┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/joseph/.config │
└──────────────────────────────────────────────────────────┘

```

Obviously this is completely unrelated to tiny-care-terminal, but by the way it works, it prevents it from getting the correct directory and thus working. Other people can also have the same or different warnings preventing standup-helper from working correctly. Also, multiple directories separated by comma doesn't seem to be working, only one is supported by the script.

**Comment by Garbee** [comment]
`npm bin -g` as used in the script works perfectly fine here. Your error seems to be related to file permissions. Have you ran `npm` or node as another user? Possibly `root` with `sudo`?

**Comment by Josephvb10** [comment]
Yeah, as I said, it's a problem related to my setup, however, something like this shouldn't break the terminal, a lot of people will never realize this problem is related to mom instead of the terminal.

**Comment by notwaldorf** [comment]
Thanks for reporting this! Unfortunately there's nothing I can do to prevent that, but I'll keep an eye out if anyone else has this problem :(
