### ISSUE TITLE
Can I replace party parrot?

### ISSUE THREAD

**Issue by JayAndCatchFire** [notwaldorf/tiny-care-terminal#4]
I know this'll probably make me _very_ unpopular, but I'm not a fan of party parrot.  Can an option be added for some other "say" script to be used in that panel?

**Comment by notwaldorf** [comment]
I could do a cow or a llama as an alternative, would that work for you?

**Comment by JayAndCatchFire** [comment]
Either works for me. Thanks!

**Comment by she-dev** [comment]
I'd love the llama!

**Comment by notwaldorf** [comment]
I have this for a llama:
```
 　 ∩∩
　（ﾟωﾟ）　ping! 
　　│ │
　　│ └─┐○
　  ヽ　　　丿
　　 　∥￣∥

```

and this for a happy cat:
```
　 ♪ ガンバレ! ♪
ミ ゛ミ ∧＿∧ ミ゛ミ
ミ ミ ( ・∀・ )ミ゛ミ
 ゛゛ ＼　　　／゛゛
 　　 　i⌒ヽ ｜
　　 　 (＿) ノ
 　　　　　 ∪
```

**Comment by rachelnicole** [comment]
There's also sign bunny! 

https://github.com/ryanbahniuk/sign-bunny

**Comment by notwaldorf** [comment]
omg @rachelnicole yes

**Comment by MichielBijl** [comment]
Happy cat makes me happy ✨.

**Comment by garymh** [comment]
I tried to use the blessed-contrib picture widget to display a custom picture (if you're not down with the parrot) but it didn't turn out that well:

<img width="1214" alt="screen shot 2017-04-21 at 1 08 02 pm" src="https://cloud.githubusercontent.com/assets/235202/25290418/9807dc0e-2693-11e7-9478-ed8afbd43be7.png">

My dog has looked better... plus I couldn't figure out the text part! Maybe someone smarter than I can use something like https://github.com/egoist/imgcat ?

**Comment by JayAndCatchFire** [comment]
It appears that imgcat lib only works on iTerm? I doubt we'd want to
restrict this package to iTerm users.

On Apr 21, 2017 1:09 PM, "Gary Holtz" <notifications@github.com> wrote:

I tried to use the blessed-contrib picture widget to display a custom
picture (if you're not down with the parrot) but it didn't turn out that
well:

[image: screen shot 2017-04-21 at 1 08 02 pm]
<https://cloud.githubusercontent.com/assets/235202/25290418/9807dc0e-2693-11e7-9478-ed8afbd43be7.png>

My dog has looked better... plus I couldn't figure out the text part! Maybe
someone smarter than I can use something like https://github.com/egoist/
imgcat ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/notwaldorf/tiny-care-terminal/issues/4#issuecomment-296263221>,
or mute the thread

**Comment by JayAndCatchFire** [comment]
It appears that [imgcat](https://github.com/egoist/imgcat) only works on iTerm? I doubt we'd want to restrict tiny-care-terminal to iTerm users.

**Comment by notwaldorf** [comment]
Yeah, I tried pretty hard to get images working and gave up, which is why I was going to stick to ascii art

**Comment by Garbee** [comment]
Sunrises, ocean waves, field of flowers, mountain landscape... Lots of ascii art that could work here to help calm people during the day.

**Comment by robertcedwards** [comment]
Where does the ascii for the parrot live?

**Comment by notwaldorf** [comment]
`tiny-care-terminal@1.1.0` now has a llama, a cat and a bunny! 🎉
