### ISSUE TITLE
Issue running standup-helper.sh

### ISSUE THREAD

**Issue by michaelbrawn** [notwaldorf/tiny-care-terminal#41]
**Node Version**: `node --version`
v4.7.2
**tiny-core-terminal version**: `npm info tiny-care-terminal | grep version:`
  version: '1.0.8'
**Shell**: `bash, zsh, fish, something else?`
zsh
**Terminal Program**: `tmux, iterm, terminator, cmd, something else?`
iterm
**Operating System**: `Mac, Windows, Linux, BSD, Really, something else?`
macOS Sierra 10.12.3

Hey, I'm having some issues with standup-helper.sh. 
In the `doTheCodes` method within care.js ([here](https://github.com/notwaldorf/tiny-care-terminal/blob/4957b0bb3acd291f8aacf7efb99ab296cd6b8450/care.js#L115)), the `spawn` call is throwing an exception
```
Error: spawn sh /Users/mbrawn/.nvm/versions/node/v4.7.2/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:355:16)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:990:3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh /Users/mbrawn/.nvm/versions/node/v4.7.2/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:355:16)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
```
Using the function mentioned in [this SO post](https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js), I was able to see the following before the exception is thrown
```
spawn called
{ '0': 'sh /Users/mbrawn/.nvm/versions/node/v4.7.2/lib/node_modules/tiny-care-terminal/standup-helper.sh',
  '1': [ '~/repos/' ],
  '2': { shell: true } }
spawn called
{ '0': 'sh /Users/mbrawn/.nvm/versions/node/v4.7.2/lib/node_modules/tiny-care-terminal/standup-helper.sh',
  '1': [ '-d 7', '~/repos/' ],
  '2': { shell: true } }
```

I am able to run the standup helper manually and get a result with sh
`sh-3.2$ ./standup_helper.sh ~/repos/`

From what I can see, I've added the environment variables
```
echo $TTC_REPOS
~/repos
```

My `.zshrc`
```
# List of accounts to read the last tweet from, comma separated
# The first in the list is read by the party parrot.
export TTC_BOTS='tinycarebot,selfcare_bot,magicrealismbot'

# List of folders to look into for `git` commits, comma separated.
export TTC_REPOS='~/repos'

# Location/zip code to check the weather for. Both 90210 and "San Francisco, CA"
# _should_ be ok (the zip code doesn't always work -- use a location
# first, if you can). It's using weather.service.msn.com behind the curtains.
export TTC_WEATHER='Toronto'

# Set to false if you're an imperial savage. <3
export TTC_CELSIUS=true

# Unset this if you _don't_ want to use Twitter keys and want to
# use web scraping instead.
export TTC_APIKEYS=true

# Refresh the dashboard every 20 minutes.
export TTC_UPDATE_INTERVAL=20

# Twitter api keys
export TTC_CONSUMER_KEY='SECRET'
export TTC_CONSUMER_SECRET='SECRET'
export TTC_ACCESS_TOKEN='SECRET'
export TTC_ACCESS_TOKEN_SECRET='SECRET'

# Note: in tiny-terminal-care < 1.0.7, the recommended variables for the Twitter
# API keys were the ones before. As of 1.0.8, they are deprecated
# (because the names are too generic), but will still be supported
# until the next major version.
# export CONSUMER_KEY='...'
# export CONSUMER_SECRET='...'
# export ACCESS_TOKEN='...'
# export ACCESS_TOKEN_SECRET='...'
```

I've tried `~/repos` and `~/repos/`

Any ideas? Have I misconfigured something?

**Comment by Garbee** [comment]
Thanks for the report, do you mind checking to see if the patch in #42 fixes the problem for you? I have a strong feeling this is due to the way the spawn call is being constructed. Not sure why it works in some environments though but not others.

**Comment by michaelbrawn** [comment]
That does prevent the exception when I [change both `today` and `week`](https://github.com/michaelbrawn/tiny-care-terminal/commit/d099b47b4f171755746fb10bcc4f5895561bf75c), but I'm not seeing any commits when loading tiny-care-terminal in iterm or terminal
![image](https://cloud.githubusercontent.com/assets/3956938/25281818/8f7dfe9a-267c-11e7-8212-dc1f78e5fbf0.png)

**Comment by KernelDeimos** [comment]
I also just received this error, and like @michaelbrawn I was using zsh. I just tried it in bash and it works fine! So, for some reason this doesn't work in zsh... I'll look into this if I have the time

**Comment by michaelbrawn** [comment]
bash and fish worked for me, but still not getting commits in any of them. It's potentially an issue with my env variables.

**Comment by notwaldorf** [comment]
@KernelDeimos I'm using oh-my-zsh, so this should work in zsh as well :(

**Comment by KernelDeimos** [comment]
So, I have no idea why this works, but replacing
`var spawn = require( 'child_process' ).spawn;`
with
`var spawn = require( 'child_process' ).exec;`
actually fixes this!

¯\_(ツ)_/¯

**Comment by aleksandar-todorovic** [comment]
@KernelDeimos is right, the hotfix from #42 helped me get rid of the first out of two messages, but the second remained. Switching `.spawn` to `.exec` helped get rid of the second error message too.

**Comment by michaelbrawn** [comment]
The changes in https://github.com/notwaldorf/tiny-care-terminal/pull/18 work for me. I also had to change my TTC_REPOS to use the absolute path to my repo directory (`/Users/username/repos/`)

**Comment by notwaldorf** [comment]
I think there are still a lot of problems with #18, so I will make the `exec` change today (and add the TTC_DEPTH while i'm at it)

**Comment by germyjen** [comment]
Ok, here are the steps I took to get my tiny care terminal to boot:

1) update the today and week (lines 119 and 127 in care.js), to match 
`var today = spawn(__dirname + '/standup-helper.sh' + config.repos, [config.repos], {shell:true});`
`var week = spawn(__dirname + '/standup-helper.sh', ['-m ' + config.depth + ' -d 7', config.repos], {shell:true});`

2) I updated the spawn as indicated in this thread to:
`var spawn = require('child_process').exec;`

3) I chmoded the git-standup.sh file:
`sudo chmod -R a+rwx /usr/local/var/nodenv/versions/4.7.0/lib/node_modules/tiny-care-terminal/standup-helper.sh`

(I'm using nodenv, update the path to match what you have locally)

Now it runs but has no content, so I'm going back to configuring the .zsh file :)

**Comment by notwaldorf** [comment]
As of version `1.2.0` there's a new way to use the terminal that doesn't involve the bash script. To use that, set the `TTC_GITBOT` environment variable to `gitlog`. This will become the default way in the future, I'm just giving it a bit of time in the wild before switching to it
