### ISSUE TITLE
Feature request: News feeds from hacker news?

### ISSUE THREAD

**Issue by hackjutsu** [notwaldorf/tiny-care-terminal#43]
**Node Version**: v6.9.1
**tiny-core-terminal version**: 1.0.8
**Shell**: zsh
**Terminal Program**: iterm2
**Operating System**: Mac

Thanks for this great tool;) Though I like the idea about adding feeds from social media, I don't use Twitter quite often. Do you have any plan to support new feeds from hacker news? Or make the feeds customizable?

Cheers~

**Comment by notwaldorf** [comment]
Thanks! I was kind of only looking to add self care things (rather than make this a generic "see whatever data you want in your terminal), and to me hacker news is quite the opposite. You can fork this (or just use blessed-contrib directly) and do something for hacker news if you want!
