### ISSUE TITLE
Startup error in care.js

### ISSUE THREAD

**Issue by hamen** [notwaldorf/tiny-care-terminal#48]
Hi,

I have just installed the app, but something is not working properly after setup. I'm getting this error:

```bash
[hamen:~] $ tiny-care-terminal

/usr/local/lib/node_modules/tiny-care-terminal/care.js:64
          forecastString = `Today, it will be ${skytextforecast} with the fore
                           ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Debug details:

**Node Version**: `v0.10.32`
**tiny-core-terminal version**: `1.0.8:`
**Shell**: `bash`
**Terminal Program**: `iTerm2 - Build 3.0.14`
**Operating System**: `OSX 10.11.6 (15G1212)`

Any help, please? Thank you!

**Comment by mojoaxel** [comment]
You have to update your node.js

**Comment by hamen** [comment]
Ouch! My bad!

Thank you, Alexander!
