### ISSUE TITLE
Add SVN Support?

### ISSUE THREAD

**Issue by BennyHarv3** [notwaldorf/tiny-care-terminal#54]
Is there a way/any chance to add SVN to this instead of just Git?

**Node Version**: 7.8.1
**tiny-core-terminal version**: 1.0.8
**Shell**: bash
**Terminal Program**: iterm
**Operating System**: Mac

Thank you!

**Comment by notwaldorf** [comment]
This is very unlikely, unless you find an npm package that does the right thing. There's a lot of support for `git`, but not a lot for `svn` that does the right thing. sorry :(

**Comment by BennyHarv3** [comment]
No worries! If I run into anything (or get inspired enough to make such a package), I'll open a pull request for it. Thanks!
