### ISSUE TITLE
Go one level deeper in searching for repos

### ISSUE THREAD

**Issue by olpeh** [notwaldorf/tiny-care-terminal#56]
**Node Version**: `v7.2.0`
**tiny-core-terminal version**: `1.0.8`
**Shell**: `bash`
**Terminal Program**: `tmux`
**Operating System**: `Linux`

For reasons I have my repositories inside `~/sites/<site-name>/public` and TCT does not find them with `TTC_REPOS` set to `~/sites`.

Would it be possible to go one level deeper?

**Comment by kisPocok** [comment]
It should work like this `~/sites/*/public`

**Comment by olpeh** [comment]
@kisPocok Thanks that seems to work. Sorry for not trying properly. I tried with `~/sites/*` before but that did not work. 

Now I just see too many times `Seems like <name> did nothing!`.

I have tens of repositories but work only on a subset of them during a week or day...
