### ISSUE TITLE
Groups are missing

### ISSUE THREAD

**Issue by kisPocok** [notwaldorf/tiny-care-terminal#57]
Hey team!

This product is awesome. However grouping doesn't work as I expected. (it's different from preview image)

My related configuration:
`export TTC_REPOS=/path/to/go/src/*`

Today window looks like:
```
Seem like (me) did nothing!
Seem like (me) did nothing!
Seem like (me) did nothing!
```

Expected:
```
/path/to/go/project-a/
  Seem like (me) did nothing!
/path/to/go/project-b/
  Seem like (me) did nothing!
/path/to/go/project-c/
  Seem like (me) did nothing!
```

**Node Version**: `v6.5.0`
**tiny-core-terminal version**: `version: '1.0.8'`
**Shell**: `.zsh`
**Terminal Program**: `iterm`
**Operating System**: `Mac`

Thank you!

**Comment by notwaldorf** [comment]
Heh, there's no team, it's just me :)
I think that's kind of expected, based on what the return of git-standup is -- in these cases it doesn't return the path, just the error. I think this should be fixed by #18, that I hope to get to very soon !
