### ISSUE TITLE
Configurable author & terminal

### ISSUE THREAD

**Issue by aripollak** [notwaldorf/tiny-care-terminal#62]
Would you add (or accept a PR to add) customization of the author passed to `git-standup`, and the ability to turn off the terminal title setting?

Thanks for this great software!

**Comment by notwaldorf** [comment]
I think turning off the terminal title is totally ok, but why would you want to look at someone else's commits? If you want to look at them, you can just run `git-standup` manually, but I'm not sure I see the point of seeing them in _this_ dashboard, that's supposed to be about your selfcare :(

**Comment by aripollak** [comment]
Ah, I originally thought `git-standup` always shows everyone's commits, but it's only because I didn't have `user.name` set in git.

**Comment by notwaldorf** [comment]
Sweet! Glad it worked! Should I close this, or do you want to send a PR for removing the title?

**Comment by aripollak** [comment]
I'll open a PR for that one. That should be configurable, not always off, right?

**Comment by notwaldorf** [comment]
@aripollak sure! put it in a `TTC_TERMINAL_TITLE` :)
