### ISSUE TITLE
Trivial: Twitter only works with lowercase handles

### ISSUE THREAD

**Issue by eighnjel** [notwaldorf/tiny-care-terminal#64]
I tried to enter a mixed case twitter handle and it wasn't working. I noticed it gets `toLowerCase()`ed when it tries to fill in the content (https://github.com/notwaldorf/tiny-care-terminal/blob/master/care.js#L92) but not when it's defined (https://github.com/notwaldorf/tiny-care-terminal/blob/master/care.js#L39-L40).

**Node Version**: 6.6.0
**tiny-core-terminal version**: 1.0.8
**Shell**: zsh
**Terminal Program**: iterm
**Operating System**: Mac

<3 Love this :D thanks for sharing!

**Comment by notwaldorf** [comment]
Oh heh, good catch! I'll get to it soon, hopefully
