### ISSUE TITLE
can't read api keys

### ISSUE THREAD

**Issue by selfagency** [notwaldorf/tiny-care-terminal#65]
I have my keys set in my fish config. I tried with and without quotes. I reset the terminal session. Weather and repos works fine. But I'm getting "Can't read Twitter without API keys" in TCT.

**Node Version**: 6.10.2
**tiny-core-terminal version**: 1.0.8
**Shell**: fish
**Terminal Program**: iTerm2
**Operating System**: Mac

**Comment by Garbee** [comment]
How exactly did you set the environment variables in fish? If you do `fish_config` can you see them in the `Variables` tab listing?

Also the screenshot isn't displaying. Perhaps try re-uploading it?

**Comment by selfagency** [comment]
Is the screenshot working now? And yes, the variables appear in fish_config.

**Comment by Garbee** [comment]
Were the variables set with the `-x` option? That is what allows them to be passed to subprocesses in fish. Looking at the config area I don't see where they explicitly show this through the UX.

The screenshot is still failing with a 410 error.

**Comment by selfagency** [comment]
![screenshot](http://danielsieradski.com/share/fish_ish.png)

**Comment by selfagency** [comment]
Hi can you still not see the screencap above?

**Comment by notwaldorf** [comment]
Have you opened a new tab or restarted your terminal, to make sure that your env variables are actually picked up?

**Comment by selfagency** [comment]
i tried again, now nearly a year later, again, setting the variables with -x and restarting my terminal. still, the api keys were not read properly and i had to opt for scraping instead.

**Comment by mojoaxel** [comment]
@selfagency Please read up on settings environment variables in fish: https://fishshell.com/docs/current/faq.html#faq-envvar

Try calling `set` before starting tct to make sure your environment variables are set.

**Comment by selfagency** [comment]
i appreciate that you're trying to help, but i know how to set variables for fish. this is all in my config.fish which loads when you open a shell.

```
set -x TTC_REPOS dev
set -x TTC_REPOS_DEPTH 1
set -x TTC_GITBOT gitlog
set -x TTC_WEATHER 13214
set -x TTC_CELSIUS false
set -x TTC_APIKEYS true
set -x TTC_UPDATE_INTERVAL 10
set -x TTC_CONSUMER_KEY [my key]
set -x TTC_CONSUMER_SECRET [my secret]
set -x TTC_ACCESS_TOKEN [my token]
set -x TTC_ACCESS_TOKEN_SECRET [my token secret]
```

everything works fine except twitter which i have to set to scrape instead, otherwise i get an error.

**Comment by mojoaxel** [comment]
> i appreciate that you're trying to help, but i know how to set variables for fish. 

:blush: Ok, Sorry! 
So let's assume it has nothing to do with the environment variables.

**Comment by mojoaxel** [comment]
I'm out of ideas here...Maybe generate a new api kay at twitter? Or try your existing key/secret with another app!?

**Comment by selfagency** [comment]
it was a brand new app with a brand new set of keys.

**Comment by mojoaxel** [comment]
You got me interested, so I installed fish (wich is nice by the way).
I had no problems with the twitter-API or anything else.

**Comment by selfagency** [comment]
closing this because it's 4 years old, twitter banned me for fighting with the nazis they refuse to ban, and i want to clean up my issues tab
