### ISSUE TITLE
Multiple repo display should be altered

### ISSUE THREAD

**Issue by safaorhan** [notwaldorf/tiny-care-terminal#66]
Hi, love this app. There's a feature request:

When I add multiple repos, and if I haven't worked some of the repos, it shows the message:

`Seems like %username% did nothing!` for each blank repo. However I have commits overall 😢 

It's ok to tell me that if I haven't worked in any of the repos but current behaviour is somehow heart-breaking and makes me feel like a lazy person 😞

This issue can be related to #17, since you said you plan to add a parent directory feature. It would be awesome.

Related image (5 repos, 1 new commit in 1 repo):

![screen shot 2017-04-26 at 09 49 05](https://cloud.githubusercontent.com/assets/4990386/25421514/f4c4f53c-2a65-11e7-80a9-76a5b3ece5a7.png)

**Comment by notwaldorf** [comment]
Awwww I'm sorry about that! That error actually comes from `git-standup`, not me :(

**Comment by Garbee** [comment]
Could we maybe intercept this output and make it say something like, `No history found for %user%.` And only say it once instead of repeated.

I'll look into that if it sounds reasonable.

**Comment by notwaldorf** [comment]
Already fixed this -- skipped the repo altogether.
