### ISSUE TITLE
Include trello cli!

### ISSUE THREAD

**Issue by antony** [notwaldorf/tiny-care-terminal#68]
It would be great if I could remove the twitter feed and replace it with my trello card info so I could view my sprint progress.

This: https://github.com/mheap/trello-cli does a great job of listing my cards. If only I could embed it!

**Node Version**: `7.9.0`
**tiny-core-terminal version**: `version: '1.0.8'`
**Shell**: `zsh`
**Terminal Program**: `gnome-terminal`
**Operating System**: `Ubuntu Linux`

Thank you!

**Comment by notwaldorf** [comment]
Hmm, I'm not super sure about including trello in _this_ dashboard -- it sounds like it could just be a completely different dashboard altogether. That sounds more like a "what work do i have to do" dashboard (and you could combine it with a list of other todos), rather than a selfcare dashboard, which I'd like this to remain.

**Comment by PrincesseLulu** [comment]
Yes good idea ! A button for switch with multiple tab

**Comment by PrincesseLulu** [comment]
Hi, in what form would you integree trello? I think working on it ..

**Comment by antony** [comment]
Well - I agree with @notwaldorf that it isn't related to the main application, but personally, I'd do something like:

1. Extract a skeleton from tiny-care-terminal which allows configurable "slots" to be used by whatever you want.
2. Make the git and trello integration "plugins" which can be slotted into the skeleton (above)

That way, tiny-care could keep on taking care, and yet we could configure it for use at say - stand-up, as a handy way of seeing what we were working on, what was coming up, what was completed etc.

People could then create different plugins, for whatever purposes they wanted. I think it would be a super-handy tool then.

As for the exact trello integration - we use it like a kan-ban board. So I'd want it to list summaries of cards in the columns "upcoming, in development, in qa, and released"

**Comment by notwaldorf** [comment]
Have you looked at blessed-contrib? That's exactly what it does -- it draws the dashboard for you, and the boxes, and you can put whatever you want in it. I really don't want to maintain a plugin dashboard framework thing :)

**Comment by antony** [comment]
I did briefly look at it - but I didn't have time to understand what tiny-care-terminal added on top.

In that case @PrincesseLulu maybe it's worth starting with `blessed-contrib` and building our own dashboard.

**Comment by PrincesseLulu** [comment]
Yes i think to, i'have download the source and i read the documentation.

**Comment by antony** [comment]
@PrincesseLulu happy to help where I can - if you want to start a repository and add me as a contributor then please do and we'll take the discussion there!

**Comment by PrincesseLulu** [comment]
Yes i do that's now

**Comment by notwaldorf** [comment]
Going to close this, since it sounds like y'all have a good plan for it. Good luck! <3
