### ISSUE TITLE
Would term-stats be a good candidate to appear in tiny-care-terminal?

### ISSUE THREAD

**Issue by abhisheksoni27** [notwaldorf/tiny-care-terminal#74]
Do you think we can add [term-stats](https://github.com/abhisheksoni27/term-stats) to `tiny-care-terminal`? (Okay maybe I am biased because I made it but..)

![term-stats](https://raw.githubusercontent.com/abhisheksoni27/term-stats/master/term-stats.gif)

**One** thing I think which could be a problem is the fact that npm download stats refresh after twenty-four hours, so there is no point in refreshing them. They'll remain the same for the rest of the day, anyway.

**Another** thing is that it could be a serious **demotivator** if you think about human psychology.

I wanna know if you'd add it, or whether it would be worth adding.

**PS:** The list of packages is configurable, of course.

**Comment by tjvr** [comment]
> Another thing is that it could be a serious demotivator if you think about human psychology.

Yeah, personally it doesn't seem to me like this would be a good fit. Nice tool though :-)

**Comment by notwaldorf** [comment]
Agreed, I really don't want to add something that says "look at all the awesome shit everyone who isn't you is building". That would personally contribute to my impostor syndrome.

Going to close this, but totally encourage you to write your own `blessed-contrib` dashboard if you want!

**Comment by abhisheksoni27** [comment]
@notwaldorf 

> I really don't want to add something that says "look at all the awesome shit everyone who isn't you is building".

Technically, the motivation for the tool was to keep an eye on how packages you have authored are performing. 

But I get it. Thanks for the response. :)
