### ISSUE TITLE
Weird symbols instead of images

### ISSUE THREAD

**Issue by bourgouinadrien** [notwaldorf/tiny-care-terminal#75]
- **Node Version**: v4.8.2
- **tiny-core-terminal version**: 1.1.1
- **Shell**: bash
- **Terminal Program**: gnome-terminal or gnome-connection-manager
- **Operating System**: Ubuntu 14.04

To see : https://i.snag.gy/BVFEAc.jpg

**Comment by Garbee** [comment]
Duplicate of #44

**Comment by bourgouinadrien** [comment]
That's right. I didn't search well.
But if we need a special font, it should be notice in readme.

**Comment by Garbee** [comment]
It isn't about just the font, but your terminal program and OS as well. It's a lot of factors which are just how terminals work. There is no way to "feature detect" and handle things gracefully.
