### ISSUE TITLE
Can't read twitter api keys

### ISSUE THREAD

**Issue by kyriejoshua** [notwaldorf/tiny-care-terminal#78]
I have set my api keys, but it says "cant read twitter". And weather and repos works fine.

![image](https://cloud.githubusercontent.com/assets/16096736/25771060/3b2c0914-3279-11e7-920b-2e53ada4c452.png)

My api key settings in '.zshrc' file like this:
![wechatimg244](https://cloud.githubusercontent.com/assets/16096736/25771157/2c09257c-327c-11e7-9ff1-00a4055e0b91.jpeg)

- **Node Version**: 6.6.0
- **tiny-core-terminal version**: 1.1.1
- **Shell**: zsh
- **Terminal Program**: iterm2
- **Operating System**: Mac

**Comment by notwaldorf** [comment]
that shooould work. Are you r keys correct? That error is thrown when authentication goes wrong, so are you sure there's no typos and stuff?

**Comment by kyriejoshua** [comment]
I am sure there's no typos and stuff. And it still can't read after I regenerate my keys and token...

**Comment by PrincesseLulu** [comment]
I have this problem to

**Comment by lorilew** [comment]
I'm having the same problem too.

**Comment by germyjen** [comment]
Hi! I'm using iTerm2 as well. I fixed this problem by completely quitting out of iTerm and restarting the application. Then, when I ran tiny care terminal, it no longer had trouble communicating with twitter. :)

**Comment by notwaldorf** [comment]
Yeah, I think you need to make sure you open a new tab, or restart iterm (to source your `.zshrc` file and pick up the new environment settings).

**Comment by kyriejoshua** [comment]
I have already restart iterm and source my `.zshrc` file, but it still no use...☹️

**Comment by kyriejoshua** [comment]
I think I find the reason why it is useless —— I live in China and we can't contact Google like this guy said…
<img width="429" alt="wx20170813-160349 2x" src="https://user-images.githubusercontent.com/16096736/29248076-436cd2cc-7fd4-11e7-9133-f9de949dccef.png">

**Comment by malditoprotozoo** [comment]
I have the same problem. The weird part is that at first it was working u.u

**Comment by mojoaxel** [comment]
Maybe it would be a good idea to make it possible to disable the whole twitter module!?
