### ISSUE TITLE
Pomodoro mode doesn't work

### ISSUE THREAD

**Issue by robrecord** [notwaldorf/tiny-care-terminal#82]
I can't get `p` Pomodoro mode to work. It doesn't do anything.

Other keys work, such as `q`.

- **Node Version**: 7.9.0
- **tiny-core-terminal version**: 1.1.1
- **Shell**: zsh
- **Terminal Program**: Terminal
- **Operating System**: MacOS Sierra

Thank you!

**Comment by Garbee** [comment]
The Pomodoro isn't in 1.1.1. That feature was merged a few days ago and the 1.1.1 version was pushed to NPM about 2 weeks ago.

**Comment by dasrecht** [comment]
Just stumbled over this too - and pressed the P-Key a lot

The easiest way to get around this is intalling it directly from github:

```
npm install -g https://github.com/notwaldorf/tiny-care-terminal.git
```

But a new release on NPM would also do it :)

Have a great day :)

**Comment by robrecord** [comment]
Thanks all!

**Comment by notwaldorf** [comment]
`1.2.0` has been released, so this should work now!
