### ISSUE TITLE
Ask you a question on the location, on the terminal show emoji for Ubuntu :)

### ISSUE THREAD

**Issue by ifzm** [notwaldorf/tiny-care-terminal#92]
Do you have a situation in the terminal that handles color emoticons ? 
If you can get your answer, it is so honored :+1: 
OS：Ubuntu 16.04 LTS

**Comment by notwaldorf** [comment]
The problem is that your OS doesn't know how to render colour emoji (this isn't a thing the dashboard can fix). 

Here's a way to enable it in Chrome, that I think should probably also work for your terminal: http://www.omgubuntu.co.uk/2016/08/enable-color-emoji-linux-google-chrome-noto

**Comment by ifzm** [comment]
Thank you for your enthusiastic answer :)

**Comment by mojoaxel** [comment]
This work for me: https://gist.github.com/mojoaxel/c6523e0969d36897367b71224c3eac7c

**Comment by ifzm** [comment]
@mojoaxel thank you. I succeeded by your way :D
