### ISSUE TITLE
Feature: Add yeoman as another option for TTC_SAY_BOX

### ISSUE THREAD

**Issue by mischah** [notwaldorf/tiny-care-terminal#94]
Hej, I love this thing 💖 

_Question:_ 
Would you accept a PR for adding Yeoman as additional option for the say box?

![image](https://cloud.githubusercontent.com/assets/441011/26152562/b3476c40-3b07-11e7-86ef-0be39659bdd3.png)

Thank you!

**Comment by notwaldorf** [comment]
I would indeed!
